name: Build and Push Docker Image

on:
  release:
    types: [created]

jobs:
  build-and-push:
    if: ${{ github.event.release.tag_name && contains(fromJSON('["dev", "uat", "prd"]'), split(github.event.release.tag_name, '_')[0]) && matches(github.event.release.tag_name, '^(dev|uat|prd)_\d+\.\d+\.\d+$') }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract environment and version
        id: meta
        run: |
          TAG=${{ github.event.release.tag_name }}
          ENV=$(echo $TAG | cut -d'_' -f1)
          VERSION=$(echo $TAG | cut -d'_' -f2)
          echo "env=$ENV" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "image_name=ghcr.io/${{ github.repository_owner }}/personal-webpage" >> $GITHUB_OUTPUT
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.image_name }}:${{ steps.meta.outputs.env }}-${{ steps.meta.outputs.version }}
            ${{ steps.meta.outputs.image_name }}:${{ steps.meta.outputs.env }}-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max